Repository ASU-CodeDevils/flameboi-slack-api, pull requests merged in 2020-03, with the labels that each got.

#3 Add README
  README.md
Labels: enhancement

#4 Studev
  .gitignore
  endpoints/install.html
  endpoints/thanks.html
  requirements.txt
  server_configs/nginx.conf
  server_configs/pathinstructions.txt
  src/app.py
  src/examplebot.py
  src/flameboi.py
  src/message.py
Labels: codebase

#5 Ignore and delete Mac Finder preferences
  .DS_Store
  .gitignore
Labels: codebase, qualityoflife

#9 Remove my personal absolute path in env instructions
  README.md
Labels: README

#10 Updated formatting to abide by MD styleguide
  README.md
  server_configs/flameboi.service
Labels: README

#15 Delete .DS_Store
  docs/.DS_Store
Labels: qualityoflife

#14 studev
  .gitignore
  command_files/__init__.py
  command_files/dice.py
  command_files/fah.py
  middleware/teach me
  requirements.txt
  server_configs/dotenvsample.txt
  server_configs/flameboi.service
  server_configs/pathinstructions.txt
  src/app.py
  src/block_kit_builder/block_generator.py
  src/connectiontester.py
  src/flameboi.py
  src/message.py
Labels: codebase

#16 studev
  .gitignore
  server_configs/deploy.sh
  server_configs/flameboi.service
  src/app.py
  src/flameboi.py
Labels: codebase

#21 studev
  server_configs/dotenvsample.txt
  src/app.py
  src/block_kit_builder/block_generator.py
  src/flameboi.py
  src/message.py
Labels: codebase
